// src/constants/assets.js

export const UNIVERSAL_PALETTE = [
  '#ffffff', '#dfe6e9', '#bdc3c7', '#95a5a6', '#7f8c8d', '#636e72', '#2d3436', '#2c3e50', '#000000',
  '#ff7675', '#d63031', '#c0392b', '#e84393', '#fd79a8',
  '#ffdbac', '#f1c27d', '#e0ac69', '#f39c12', '#e67e22', '#d35400', '#8d5524', '#523826', '#5d4037', 
  '#ffeaa7', '#f1c40f', 
  '#55efc4', '#00b894', '#00cec9', '#1abc9c', '#16a085', '#2ecc71', '#27ae60', '#6ab04c',
  '#74b9ff', '#0984e3', '#2980b9', '#3498db', '#34495e', '#48dbfb',
  '#a29bfe', '#6c5ce7', '#8e44ad', '#9b59b6', 
];

export const PALETTES = {
  skin: UNIVERSAL_PALETTE.filter(c => ['#ffdbac', '#f1c27d', '#e0ac69', '#8d5524', '#523826', '#6ab04c', '#48dbfb', '#a29bfe', '#b2bec3', '#eb4d4b', '#2d3436', '#dfe6e9', '#ffffff'].includes(c) || true), 
  hair: UNIVERSAL_PALETTE,
  outfit: UNIVERSAL_PALETTE,
  shoes: UNIVERSAL_PALETTE,
  eyes: UNIVERSAL_PALETTE,
  monster: UNIVERSAL_PALETTE,
  metal: UNIVERSAL_PALETTE,
};

export const TRANSLATIONS = {
  en: {
    title: "RPG Sprite Maker",
    subtitle: "Create your 8-bit hero or monster",
    anim: "Anim",
    random: "Random",
    download: "Download PNG",
    core: "Core",
    bit16: "16-BIT",
    race: "Race",
    chest: "Chest",
    waist: "Waist",
    appearance: "Appearance",
    skinTone: "Skin Tone",
    hairStyle: "Hair Style",
    hairColor: "Hair Color",
    eyes: "Eyes",
    eyeColor: "Eye Color",
    outfit: "Outfit",
    chestColor: "Chest Color",
    waistColor: "Waist Color",
    pantsColor: "Pants Color",
    shoes: "Shoes",
    shoeColor: "Shoe Color",
    accessories: "Accessories",
    head: "Head",
    eye: "Eye",
    face: "Face",
    faceShape: "Face Shape",
    ear: "Ear",
    monsterParts: "Monster Parts",
    horns: "Horns",
    wings: "Wings",
    tail: "Tail",
    partsColor: "Parts Color",
    fangs: "Fangs",
    claws: "Claws",
    equipment: "Equipment",
    weapon: "Weapon",
    shield: "Shield",
    helmet: "Helmet",
    weaponColor: "Weapon Color",
    shieldColor: "Shield Color",
    helmetColor: "Helmet Color",
    
    bitMode: "Quality",
    bitModes: ['8-BIT', '16-BIT', '32-BIT'],
    reset: "Reset",

    races: ['Human', 'Slime', 'Skeleton', 'Ghost', 'Goblin', 'Lizardman', 'Birdman', 'Demon', 'Elf', 'Dwarf'],
    chestOpt: ['Bare', 'Tunic', 'Armor', 'Robe', 'Coat', 'Bikini'],
    // Bare を追加
    waistOpt: ['Pants Only', 'Belt', 'Skirt', 'Loincloth', 'Armor Skirt', 'Bare'],
    hairStyles: ['Short', 'Long', 'Spiky', 'Bob', 'Skinhead'], 

    faceShapes: ['Normal', 'Round', 'Square', 'Long'],

    eyeStyles: [
      'Normal', 'Big', 'Small', 'Narrow', 'Cat'
    ],
    shoeStyles: ['Barefoot', 'Shoes', 'Boots'],
    accHead: ['None', 'Cat Ears', 'Crown'],
    accEye: ['None', 'Glasses', 'Sunglasses', 'Monocle', 'Scouter', 'Eyepatch'],
    accEar: ['None', 'Gold Ring', 'Silver Stud', 'Red Gem', 'Blue Gem'],
    optHorns: ['None', 'Small', 'Bull', 'Unicorn', 'Demon', 'Ram', 'Antlers'],
    optWings: ['None', 'Bat', 'Angel', 'Fairy', 'Dragon', 'Butterfly', 'Demon'],
    optTail: ['None', 'Demon', 'Beast', 'Lizard', 'Fox', 'Cat'],
    optWeapon: ['None', 'Sword', 'Staff', 'Bow', 'Spear', 'Axe', 'Dagger'],
    optShield: ['None', 'Buckler', 'Kite Shield', 'Tower Shield'],
    optHelmet: ['None', 'Iron Helm', 'Viking', 'Mage Hat', 'Hood'],
  },
  ja: {
    title: "RPG スプライトメーカー",
    subtitle: "8bit風の勇者やモンスターを作ろう",
    anim: "アニメ",
    random: "ランダム",
    download: "PNG保存",
    core: "基本設定",
    bit16: "16-BIT (陰影)",
    race: "種族",
    chest: "胸 (上半身)",
    waist: "腰 (下半身)",
    appearance: "外見",
    skinTone: "肌の色",
    hairStyle: "髪型",
    hairColor: "髪色",
    eyes: "目の形",
    eyeColor: "目の色",
    outfit: "服装",
    chestColor: "胸の色",
    waistColor: "腰の色",
    pantsColor: "ズボンの色",
    shoes: "靴",
    shoeColor: "靴の色",
    accessories: "アクセサリー",
    head: "頭",
    eye: "目",
    face: "顔",
    faceShape: "顔の形",
    ear: "耳",
    monsterParts: "モンスターパーツ",
    horns: "ツノ",
    wings: "羽",
    tail: "尻尾",
    partsColor: "パーツの色",
    fangs: "牙",
    claws: "爪",
    equipment: "装備",
    weapon: "武器",
    shield: "盾",
    helmet: "兜・帽子",
    weaponColor: "武器の色",
    shieldColor: "盾の色",
    helmetColor: "兜の色",
    
    bitMode: "画質",
    bitModes: ['8-BIT (単色)', '16-BIT (陰影)', '32-BIT (高画質)'],
    reset: "リセット",

    races: ['人間', 'スライム', 'スケルトン', 'ゴースト', 'ゴブリン', 'リザードマン', '鳥人', '悪魔', 'エルフ', 'ドワーフ'],
    chestOpt: ['裸', 'チュニック', '鎧', 'ローブ', 'コート', 'ビキニ'],
    // 裸 を追加
    waistOpt: ['ズボンのみ', 'ベルト', 'スカート', '腰布', '垂れ', '裸'],
    hairStyles: ['ショート', 'ロング', 'ツンツン', 'ボブ', 'スキンヘッド'],

    faceShapes: ['普通', '丸顔', '四角', '面長'],

    eyeStyles: [
      '普通', '大きい', '小さい', '細目', '猫目'
    ],
    shoeStyles: ['裸足', '靴', 'ブーツ'],
    accHead: ['なし', '猫耳', '王冠'],
    accEye: ['なし', 'メガネ', 'サングラス', 'モノクル', 'スカウター', '眼帯'],
    accEar: ['なし', '金の輪', '銀の鋲', '赤宝石', '青宝石'],
    optHorns: ['なし', '小', '牛', 'ユニコーン', '悪魔', '羊', '鹿'],
    optWings: ['なし', 'コウモリ', '天使', '妖精', 'ドラゴン', '蝶', '悪魔'],
    optTail: ['なし', '悪魔', '獣', 'トカゲ', '狐', '猫'],
    optWeapon: ['なし', '剣', '杖', '弓', '槍', '斧', '短剣'],
    optShield: ['なし', '小盾', 'カイト', '大盾'],
    optHelmet: ['なし', '鉄兜', 'バイキング', '帽子', 'フード'],
  }
};